export const CROPS = [
  {id:'paddy',emoji:'🌾',name:'Paddy (Rice)',te:'వరి',bg:'linear-gradient(135deg,#dcfce7,#bbf7d0)',
   soils:['Loamy','Alluvial','Clay'],seasons:['Kharif'],water:['High','Medium'],
   yield:'20–25 qtl/acre',dur:'120–150 days',tags:['best','risk'],avgPrice:2183,minPrice:2100,maxPrice:2500,demand:'High',
   desc:'Paddy is the staple food crop of Andhra Pradesh. It thrives in areas with abundant water supply and warm climate. AP is one of India\'s leading paddy producers with Krishna and Godavari deltas being prime regions.',
   idealSoil:'Clay Loam, Alluvial',idealClimate:'20–37°C, 150cm+ rainfall',
   stages:[{n:'Nursery',d:'0–21d',ic:'🌱',on:true},{n:'Transplant',d:'21–30d',ic:'🪴',on:true},{n:'Tillering',d:'30–60d',ic:'🌿',on:true},{n:'Panicle',d:'60–90d',ic:'🌾',on:false},{n:'Harvest',d:'120–150d',ic:'🌾',on:false}],
   ferts:[{n:'Urea (N)',dose:'120 kg/acre',t:'Basal + 2 split'},{n:'DAP (P₂O₅)',dose:'24 kg/acre',t:'Basal'},{n:'MOP (K₂O)',dose:'40 kg/acre',t:'Basal + 1 split'},{n:'Zinc Sulphate',dose:'10 kg/acre',t:'Once in 3 yrs'}],
   water_req:[{l:'Irrigation',v:90},{l:'Drainage',v:70},{l:'Critical period',v:85}],
   profit:{months:['Jun','Jul','Aug','Sep','Oct'],income:[0,0,5000,8000,45000]},
   pests:[{ic:'🦟',n:'Brown Plant Hopper',sym:'Yellowing and drying of plants in patches ("hopper burn")',trt:'Spray Imidacloprid 17.8 SL @ 0.3ml/L water'},{ic:'🐛',n:'Stem Borer',sym:'Dead hearts in vegetative stage; white ears in reproductive stage',trt:'Spray Cartap hydrochloride 50 SP @ 2g/L'},{ic:'🍄',n:'Blast Disease',sym:'Diamond-shaped grey-centred lesions on leaves',trt:'Spray Tricyclazole 75 WP @ 0.6g/L'}],
   mktNote:'Consistent demand due to food security. MSP support ensures minimum returns. Export opportunities to Gulf countries.'},
  {id:'cotton',emoji:'🌿',name:'Cotton',te:'పత్తి',bg:'linear-gradient(135deg,#f0fdf4,#d1fae5)',
   soils:['Black'],seasons:['Kharif'],water:['Low','Medium'],
   yield:'8–12 qtl/acre',dur:'150–180 days',tags:['best','profit'],avgPrice:6700,minPrice:6200,maxPrice:7500,demand:'Medium',
   desc:'Cotton is the "White Gold" of AP. The black soil belt is ideally suited for cotton cultivation. High market demand and strong export links to the textile industry make it one of the most profitable Kharif crops.',
   idealSoil:'Deep Black Soil (Regur)',idealClimate:'21–30°C, 60–110cm rainfall',
   stages:[{n:'Germination',d:'0–10d',ic:'🌱',on:true},{n:'Seedling',d:'10–30d',ic:'🪴',on:true},{n:'Squaring',d:'30–60d',ic:'🌿',on:false},{n:'Boll Form',d:'60–120d',ic:'🌸',on:false},{n:'Harvest',d:'150–180d',ic:'🌿',on:false}],
   ferts:[{n:'Urea (N)',dose:'80 kg/acre',t:'3 split doses'},{n:'SSP (P)',dose:'50 kg/acre',t:'Basal'},{n:'MOP (K)',dose:'40 kg/acre',t:'Basal + 1 split'},{n:'Boron',dose:'1 kg/acre',t:'Foliar at flowering'}],
   water_req:[{l:'Germination',v:40},{l:'Squaring',v:75},{l:'Boll Dev',v:88}],
   profit:{months:['Jun','Aug','Oct','Dec','Jan'],income:[0,0,10000,50000,75000]},
   pests:[{ic:'🔴',n:'Bollworm',sym:'Bore holes in bolls, shedding of squares and flowers',trt:'Spray Emamectin benzoate 5 SG @ 0.4g/L'},{ic:'⬛',n:'Whitefly',sym:'Yellowing leaves, honeydew deposits, sooty mould',trt:'Spray Thiamethoxam 25 WG @ 0.5g/L'},{ic:'🟤',n:'Bacterial Blight',sym:'Water-soaked angular spots turning brown on leaves',trt:'Spray Copper oxychloride 50 WP @ 3g/L'}],
   mktNote:'Cotton prices are volatile but tend to be above MSP in most years. Textile export demand from India is consistently strong.'},
  {id:'chilli',emoji:'🌶️',name:'Chilli',te:'మిర్చి',bg:'linear-gradient(135deg,#fff1f2,#fecdd3)',
   soils:['Red','Sandy','Loamy'],seasons:['Rabi','Kharif'],water:['Medium','High'],
   yield:'15–20 qtl/acre (dry)',dur:'160–200 days',tags:['profit','best'],avgPrice:8200,minPrice:7500,maxPrice:10000,demand:'High',
   desc:'Guntur chilli is world-famous! AP produces about 50% of India\'s total chilli. A highly profitable crop with strong domestic and international demand. Guntur Sannam variety is especially prized in global markets.',
   idealSoil:'Sandy Loam, Red Sandy',idealClimate:'20–30°C, 60–120cm rainfall',
   stages:[{n:'Nursery',d:'0–30d',ic:'🌱',on:true},{n:'Transplant',d:'30–45d',ic:'🪴',on:true},{n:'Vegetative',d:'45–90d',ic:'🌿',on:true},{n:'Flowering',d:'90–130d',ic:'🌸',on:false},{n:'Harvest',d:'160–200d',ic:'🌶️',on:false}],
   ferts:[{n:'Urea (N)',dose:'100 kg/acre',t:'4 split doses'},{n:'DAP (P)',dose:'40 kg/acre',t:'Basal'},{n:'MOP (K)',dose:'60 kg/acre',t:'Basal + 2 split'},{n:'Calcium Nitrate',dose:'5 kg/acre',t:'2 foliar sprays'}],
   water_req:[{l:'Transplanting',v:85},{l:'Flowering',v:90},{l:'Fruit Dev',v:95}],
   profit:{months:['Oct','Nov','Dec','Jan','Feb'],income:[0,5000,15000,65000,80000]},
   pests:[{ic:'🦠',n:'Thrips',sym:'Silvery streaks, curling and distortion of buds and leaves',trt:'Spray Fipronil 5 SC @ 2ml/L or Spinosad 45 SC'},{ic:'🔴',n:'Mites',sym:'Yellow stippling on leaves, webbing on underside',trt:'Spray Abamectin 1.8 EC @ 0.5ml/L'},{ic:'🍄',n:'Anthracnose',sym:'Circular dark sunken spots on fruits',trt:'Spray Mancozeb 75 WP @ 2.5g/L'}],
   mktNote:'Guntur chilli commands premium prices nationally and internationally. Export to USA, UK, and Gulf is consistently strong.'},
  {id:'maize',emoji:'🌽',name:'Maize (Corn)',te:'మొక్కజొన్న',bg:'linear-gradient(135deg,#fefce8,#fef9c3)',
   soils:['Loamy','Sandy','Red'],seasons:['Kharif','Rabi'],water:['Medium'],
   yield:'20–30 qtl/acre',dur:'90–110 days',tags:['risk','profit'],avgPrice:1850,minPrice:1700,maxPrice:2100,demand:'Medium',
   desc:'Maize is a versatile short-duration crop used for food, feed, and industrial purposes. Growing demand from the poultry feed industry and starch manufacturers makes it an excellent choice for crop rotation.',
   idealSoil:'Sandy Loam, Well-drained Loam',idealClimate:'21–27°C, 60–90cm rainfall',
   stages:[{n:'Germination',d:'0–7d',ic:'🌱',on:true},{n:'Vegetative',d:'7–45d',ic:'🌿',on:true},{n:'Tasseling',d:'45–65d',ic:'🌾',on:false},{n:'Silking',d:'65–75d',ic:'🌽',on:false},{n:'Harvest',d:'90–110d',ic:'🌽',on:false}],
   ferts:[{n:'Urea (N)',dose:'130 kg/acre',t:'Basal + knee-high + tasseling'},{n:'DAP (P)',dose:'50 kg/acre',t:'Basal'},{n:'MOP (K)',dose:'30 kg/acre',t:'Basal'},{n:'Sulphur',dose:'20 kg/acre',t:'Basal (alternate years)'}],
   water_req:[{l:'Emergence',v:55},{l:'Tasseling',v:90},{l:'Grain Fill',v:85}],
   profit:{months:['Jun','Jul','Aug','Sep'],income:[0,2000,4000,35000]},
   pests:[{ic:'🪲',n:'Fall Armyworm',sym:'Window-pane damage on leaves, ragged feeding with frass in whorl',trt:'Spray Emamectin 5 SG @ 0.4g/L in whorl'},{ic:'🐛',n:'Stem Borer',sym:'Dead hearts in young plants, bore holes with frass',trt:'Carbofuran 3G @ 7kg/acre in whorl'}],
   mktNote:'Steady demand from poultry, starch, and ethanol industries. Prices relatively stable. Good option for contract farming.'},
  {id:'groundnut',emoji:'🫘',name:'Groundnut',te:'వేరుశనగ',bg:'linear-gradient(135deg,#fff7ed,#ffedd5)',
   soils:['Sandy','Red','Loamy'],seasons:['Kharif','Rabi'],water:['Low','Medium'],
   yield:'8–12 qtl/acre',dur:'90–120 days',tags:['risk','profit'],avgPrice:5400,minPrice:5000,maxPrice:6000,demand:'High',
   desc:'Groundnut is the major oilseed crop of AP. Kurnool district is famous for production. Drought-tolerant nature makes it ideal for rainfed areas. High demand for oil, confectionery, and export to China.',
   idealSoil:'Sandy Loam, Light Red',idealClimate:'25–30°C, 50–75cm rainfall',
   stages:[{n:'Germination',d:'0–10d',ic:'🌱',on:true},{n:'Vegetative',d:'10–35d',ic:'🌿',on:true},{n:'Flowering',d:'35–55d',ic:'🌸',on:false},{n:'Peg Stage',d:'55–80d',ic:'🫘',on:false},{n:'Harvest',d:'90–120d',ic:'🫘',on:false}],
   ferts:[{n:'SSP (P+S)',dose:'100 kg/acre',t:'Basal – provides P & S'},{n:'MOP (K)',dose:'20 kg/acre',t:'Basal'},{n:'Gypsum',dose:'80 kg/acre',t:'At pegging stage – critical!'},{n:'Rhizobium',dose:'1 packet/10kg seed',t:'Seed treatment'}],
   water_req:[{l:'Germination',v:60},{l:'Flowering',v:80},{l:'Pod Fill',v:75}],
   profit:{months:['Jun','Jul','Aug','Sep','Oct'],income:[0,0,3000,10000,42000]},
   pests:[{ic:'🦟',n:'Aphids',sym:'Curling of leaves, stunted growth, honeydew deposits',trt:'Spray Dimethoate 30 EC @ 2ml/L water'},{ic:'🔵',n:'Tikka Disease',sym:'Brown circular leaf spots – early and late leaf spot',trt:'Spray Chlorothalonil 75 WP @ 2g/L'}],
   mktNote:'Strong domestic demand for edible oil. Export to China and Southeast Asia growing. MSP provides safety net for farmers.'},
  {id:'sunflower',emoji:'🌻',name:'Sunflower',te:'పొద్దుతిరుగుడు',bg:'linear-gradient(135deg,#fefce8,#fef08a)',
   soils:['Loamy','Black','Red'],seasons:['Rabi','Zaid'],water:['Low','Medium'],
   yield:'5–7 qtl/acre',dur:'90–100 days',tags:['risk'],avgPrice:4100,minPrice:3800,maxPrice:4500,demand:'Low',
   desc:'Sunflower is an important oilseed crop for the Rabi season. High oil content (40-45%) and short duration make it an excellent rotation crop. AP government supports cultivation with subsidies on hybrid seeds.',
   idealSoil:'Well-drained Loam to Sandy Loam',idealClimate:'18–25°C, 40–80cm rainfall',
   stages:[{n:'Germination',d:'0–7d',ic:'🌱',on:true},{n:'Vegetative',d:'7–35d',ic:'🌿',on:true},{n:'Bud Stage',d:'35–55d',ic:'🌸',on:false},{n:'Flowering',d:'55–70d',ic:'🌻',on:false},{n:'Maturity',d:'90–100d',ic:'🌻',on:false}],
   ferts:[{n:'Urea (N)',dose:'55 kg/acre',t:'Basal + knee-high'},{n:'SSP (P)',dose:'50 kg/acre',t:'Basal'},{n:'MOP (K)',dose:'33 kg/acre',t:'Basal'},{n:'Boron',dose:'0.5 kg/acre',t:'Foliar at bud initiation'}],
   water_req:[{l:'Germination',v:50},{l:'Bud Stage',v:85},{l:'Seed Fill',v:80}],
   profit:{months:['Oct','Nov','Dec','Jan'],income:[0,2000,5000,30000]},
   pests:[{ic:'🐛',n:'Head Borer',sym:'Tunneling into flower head, premature drying of head',trt:'Spray Chlorpyrifos 20 EC @ 2ml/L'},{ic:'🍄',n:'Downy Mildew',sym:'Yellow angular leaf lesions; white fungal growth below',trt:'Metalaxyl+Mancozeb seed treatment + foliar spray'}],
   mktNote:'Demand driven by edible oil market. Import competition keeps prices moderate. Best used in rotation for soil health benefits.'},
];

export const RULES = [
  {soil:'Black',season:'Kharif',water:['Low','Medium','High'],ids:['cotton','maize']},
  {soil:'Black',season:'Rabi',water:['Low','Medium'],ids:['sunflower','groundnut']},
  {soil:'Red',season:'Kharif',water:['Medium','High'],ids:['chilli','groundnut']},
  {soil:'Red',season:'Rabi',water:['Low','Medium'],ids:['sunflower','groundnut']},
  {soil:'Sandy',season:'Kharif',water:['Low','Medium'],ids:['groundnut','maize']},
  {soil:'Sandy',season:'Rabi',water:['Low','Medium'],ids:['sunflower','chilli']},
  {soil:'Loamy',season:'Kharif',water:['High','Medium'],ids:['paddy','maize','chilli']},
  {soil:'Loamy',season:'Rabi',water:['Medium','High'],ids:['chilli','sunflower','maize']},
  {soil:'Loamy',season:'Zaid',water:['High'],ids:['maize','groundnut']},
  {soil:'Alluvial',season:'Kharif',water:['High'],ids:['paddy','maize']},
  {soil:'Clay',season:'Kharif',water:['High','Medium'],ids:['paddy']},
];
